package com.stitch.admin.model.enums;

public enum Permissions {

    PERM_CREATE_ADMIN,
    PERM_CREATE_ROLE,
    PERM_REVOKE_ROLE,
    PERM_CREATE_PERM,
    PERM_ASSIGN_PERM,
    PERM_REMOVE_PERM,
    PERM_ASSIGN_ROLE,
    PERM_VIEW_ROLES,
    PERM_VIEW_PERMS,
    PERM_DEACTIVATE_USER,
    PERM_UPDATE_USER,
    PERM_UPDATE_PSW,
    PERM_DEFAULT
}
